// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace fpm_for_VS
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidfpm_for_VSPackageString = "3866e555-61c7-4dee-bfac-7e1f88e0242c";
        public static Guid guidfpm_for_VSPackage = new Guid(guidfpm_for_VSPackageString);

        public const string guidfpm_for_VSPackageCmdSetString = "4d594205-be54-4121-ad39-83e60f7738aa";
        public static Guid guidfpm_for_VSPackageCmdSet = new Guid(guidfpm_for_VSPackageCmdSetString);

        public const string buildImagesString = "be4c33a9-abf7-40d9-8e0b-9fcee64b7494";
        public static Guid buildImages = new Guid(buildImagesString);

        public const string testImagesString = "7bf4e15f-30ca-48f6-a3f4-537324806fcc";
        public static Guid testImages = new Guid(testImagesString);

        public const string runImagesString = "8b578d0b-027b-48ad-ad86-be31509e3455";
        public static Guid runImages = new Guid(runImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int fpmMenu = 0x1021;
        public const int fpmCommands = 0x1020;
        public const int buildId = 0x0100;
        public const int testId = 0x0101;
        public const int runId = 0x0102;
        public const int buildIcon = 0x0001;
        public const int testIcon = 0x0001;
        public const int runIcon = 0x0001;
    }
}